#include "pch.h"
#include "global.h"

tTransform g_transform = {};
tGlobal GlobalData = {};



extern const char* RES_TYPE_STR[(UINT)RES_TYPE::END] =
{
	"MESHDATA",
	"MATERIAL",
	"PREFAB",
	"MESH",
	"TEXTURE",
	"SOUND",
	"GRAPHICS_SHADER",
	"COMPUTE_SHADER"
};

extern const wchar_t* RES_TYPE_WSTR[(UINT)RES_TYPE::END] =
{
	L"MESHDATA",
	L"MATERIAL",
	L"PREFAB",
	L"MESH",
	L"TEXTURE",
	L"SOUND",
	L"GRAPHICS_SHADER",
	L"COMPUTE_SHADER"
};

extern const char* COMPONENT_TYPE_STR[(UINT)COMPONENT_TYPE::END] =
{
	"TRANSFORM",
	"COLLIDER3D",
	"RIGIDBODY",
	"ANIMATOR3D",
	"ANIMATOR2D",
	"LIGHT3D",
	"PATHFIND",
	"GIZMO",
	"CAMERA",

	"MESHRENDER",
	"PARTICLESYSTEM",
	"LANDSCAPE",
	"SKYBOX",
	"DECAL",
};

extern const wchar_t* COMPONENT_TYPE_WSTR[(UINT)COMPONENT_TYPE::END] =
{
	L"TRANSFORM",
	L"COLLIDER3D",
	L"RIGIDBODY",
	L"ANIMATOR3D",
	L"ANIMATOR2D",
	L"LIGHT3D",
	L"PATHFIND",
	L"GIZMO",
	L"CAMERA",

	L"MESHRENDER",
	L"PARTICLESYSTEM",
	L"LANDSCAPE",
	L"SKYBOX",
	L"DECAL",
};

extern const char* GUN_ANIMATION_TYPE_STR[(UINT)GUN_ANIMATION_TYPE::END + 1] =
{
	"FIRE",
	"RELOAD",
	"FAST_RELOAD",
	"IDLE",
	"DRAW",
	"END",
};

extern const wchar_t* GUN_ANIMATION_TYPE_WSTR[(UINT)GUN_ANIMATION_TYPE::END + 1] =
{
	L"FIRE",
	L"RELOAD",
	L"FAST_RELOAD",
	L"IDLE",
	L"DRAW",
	L"END",
};
extern const char* WARRIOR_ANIMATION_TYPE_STR[(UINT)WARRIOR_ANIMATION_TYPE::END + 1] =
{
	"ENTER",
	"IDLE",
	"DIE",
	"FAR_BREATH",
	"MID_BREATH",
	"NEAR_BREATH",
	"TAIL_BEAM_ENTER",
	"TAIL_BEAM_IDLE",
	"TAIL_BEAM_EXIT",
	"TAIL_ATTACK",
	"ROCK_THROW",
	"END",
};
extern const wchar_t* WARRIOR_ANIMATION_TYPE_WSTR[(UINT)WARRIOR_ANIMATION_TYPE::END + 1] =
{
	L"ENTER",
	L"IDLE",
	L"DIE",
	L"FAR_BREATH",
	L"MID_BREATH",
	L"NEAR_BREATH",
	L"TAIL_BEAM_ENTER",
	L"TAIL_BEAM_IDLE",
	L"TAIL_BEAM_EXIT",
	L"TAIL_ATTACK",
	L"ROCK_THROW",
	L"END",
};
extern const char* ENEMY_ANIMATION_TYPE_STR[(UINT)ENEMY_ANIMATION_TYPE::END + 1] =
{
	"WALK_FORWARD",
	"WALK_BACK",
	"WALK_RIGHT",
	"WALK_LEFT",
	"SPRINT_FORWARD",
	"IDLE",
	"FIRE",
	"LOOK",
	"LOOK_RIGHT",
	"LOOK_LEFT",
	"LOOK_BACK",
	"RELOAD",
	"MELEE",
	"DIE",
	"END",
};
extern const wchar_t* ENEMY_ANIMATION_TYPE_WSTR[(UINT)ENEMY_ANIMATION_TYPE::END + 1] =
{
	L"WALK_FORWARD",
	L"WALK_BACK",
	L"WALK_RIGHT",
	L"WALK_LEFT",
	L"SPRINT_FORWARD",
	L"IDLE",
	L"FIRE",
	L"LOOK",
	L"LOOK_RIGHT",
	L"LOOK_LEFT",
	L"LOOK_BACK",
	L"RELOAD",
	L"MELEE",
	L"DIE",
	L"END",
};
extern const char* PLAYER_ANIMATION_TYPE_STR[(UINT)PLAYER_ANIMATION_TYPE::END + 1] =
{
	"WALK_FORWARD",
	"SNIPER_WALK_FORWARD",
	"PISTOL_WALK_FORWARD",
	"WALK_BACK",
	"SNIPER_WALK_BACK",
	"PISTOL_WALK_BACK",
	"WALK_RIGHT",
	"SNIPER_WALK_RIGHT",
	"PISTOL_WALK_RIGHT",
	"WALK_LEFT",
	"SNIPER_WALK_LEFT",
	"PISTOL_WALK_LEFT",
	"RUN_FORWARD",
	"SNIPER_RUN_FORWARD",
	"PISTOL_RUN_FORWARD",
	"JUMP",
	"SNIPER_JUMP",
	"PISTOL_JUMP",
	"IDLE",
	"SNIPER_IDLE",
	"PISTOL_IDLE",
	"DRAW",
	"SNIPER_DRAW",
	"PISTOL_DRAW",
	"RELOAD",
	"SNIPER_RELOAD",
	"PISTOL_RELOAD",
	"FAST_RELOAD",
	"SNIPER_FAST_RELOAD",
	"PISTOL_FAST_RELOAD",
	"SIGHT_IDLE",
	"SNIPER_SIGHT_IDLE",
	"PISTOL_SIGHT_IDLE",
	"SIGHT_F",
	"SNIPER_SIGHT_F",
	"PISTOL_SIGHT_F",
	"GRENADE_THROW",
	"SNIPER_GRENADE_THROW",
	"PISTOL_GRENADE_THROW",
	"MELEE",
	"SNIPER_MELEE",
	"PISTOL_MELEE",
	"FIRE",
	"SNIPER_FIRE",
	"PISTOL_FIRE",
	"DIE",
	"DEAD",
	"NONE",
};

extern const wchar_t* PLAYER_ANIMATION_TYPE_WSTR[(UINT)PLAYER_ANIMATION_TYPE::END + 1] =
{
	L"WALK_FORWARD",
	L"SNIPER_WALK_FORWARD",
	L"PISTOL_WALK_FORWARD",
	L"WALK_BACK",
	L"SNIPER_WALK_BACK",
	L"PISTOL_WALK_BACK",
	L"WALK_RIGHT",
	L"SNIPER_WALK_RIGHT",
	L"PISTOL_WALK_RIGHT",
	L"WALK_LEFT",
	L"SNIPER_WALK_LEFT",
	L"PISTOL_WALK_LEFT",
	L"RUN_FORWARD",
	L"SNIPER_RUN_FORWARD",
	L"PISTOL_RUN_FORWARD",
	L"JUMP",
	L"SNIPER_JUMP",
	L"PISTOL_JUMP",
	L"IDLE",
	L"SNIPER_IDLE",
	L"PISTOL_IDLE",
	L"DRAW",
	L"SNIPER_DRAW",
	L"PISTOL_DRAW",
	L"RELOAD",
	L"SNIPER_RELOAD",
	L"PISTOL_RELOAD",
	L"FAST_RELOAD",
	L"SNIPER_FAST_RELOAD",
	L"PISTOL_FAST_RELOAD",
	L"SIGHT_IDLE",
	L"SNIPER_SIGHT_IDLE",
	L"PISTOL_SIGHT_IDLE",
	L"SIGHT_F",
	L"SNIPER_SIGHT_F",
	L"PISTOL_SIGHT_F",
	L"GRENADE_THROW",
	L"SNIPER_GRENADE_THROW",
	L"PISTOL_GRENADE_THROW",
	L"MELEE",
	L"SNIPER_MELEE",
	L"PISTOL_MELEE",
	L"FIRE",
	L"SNIPER_FIRE",
	L"PISTOL_FIRE",
	L"DIE",
	L"DEAD",
	L"NONE",
};
