#include "pch.h"
#include "global.h"

tTransform g_transform = {};
tGlobal GlobalData = {};



extern const char* RES_TYPE_STR[(UINT)RES_TYPE::END] =
{
	"MESHDATA",
	"MATERIAL",
	"PREFAB",
	"MESH",
	"TEXTURE",
	"SOUND",
	"GRAPHICS_SHADER",
	"COMPUTE_SHADER"
};

extern const wchar_t* RES_TYPE_WSTR[(UINT)RES_TYPE::END] =
{
	L"MESHDATA",
	L"MATERIAL",
	L"PREFAB",
	L"MESH",
	L"TEXTURE",
	L"SOUND",
	L"GRAPHICS_SHADER",
	L"COMPUTE_SHADER"
};

extern const char* COMPONENT_TYPE_STR[(UINT)COMPONENT_TYPE::END] =
{
	"TRANSFORM",
	"COLLIDER3D",
	"RIGIDBODY",
	"ANIMATOR3D",
	"LIGHT3D",
	"PATHFIND",
	"GIZMO",
	"CAMERA",

	"MESHRENDER",
	"PARTICLESYSTEM",
	"LANDSCAPE",
	"SKYBOX",
	"DECAL",
};

extern const wchar_t* COMPONENT_TYPE_WSTR[(UINT)COMPONENT_TYPE::END] =
{
	L"TRANSFORM",
	L"COLLIDER3D",
	L"RIGIDBODY",
	L"ANIMATOR3D",
	L"LIGHT3D",
	L"PATHFIND",
	L"GIZMO",
	L"CAMERA",

	L"MESHRENDER",
	L"PARTICLESYSTEM",
	L"LANDSCAPE",
	L"SKYBOX",
	L"DECAL",
};

extern const char* GUN_ANIMATION_TYPE_STR[(UINT)GUN_ANIMATION_TYPE::END + 1] =
{
	"FIRE",
	"RELOAD",
	"FAST_RELOAD",
	"IDLE",
	"END",
};

extern const wchar_t* GUN_ANIMATION_TYPE_WSTR[(UINT)GUN_ANIMATION_TYPE::END + 1] =
{
	L"FIRE",
	L"RELOAD",
	L"FAST_RELOAD",
	L"IDLE",
	L"END",
};

extern const char* ANIMATION_TYPE_STR[(UINT)ANIMATION_TYPE::END + 1] =
{
	"WALK_FORWARD",
	"WALK_BACK",
	"WALK_RIGHT",
	"WALK_LEFT",
	"RUN_FORWARD",
	"RUN_BACK",
	"RUN_RIGHT",
	"RUN_LEFT",
	"JUMP",
	"IDLE",
	"ATTACK1",
	"ATTACK2",
	"ATTACK3",
	"ATTACK4",
	"DIE",
	"DEAD",
	"EXTRA1",
	"EXTRA2",
	"EXTRA3",
	"EXTRA4",
	"NONE",
};

extern const wchar_t* ANIMATION_TYPE_WSTR[(UINT)ANIMATION_TYPE::END + 1] =
{
	L"WALK_FORWARD",
	L"WALK_BACK",
	L"WALK_RIGHT",
	L"WALK_LEFT",
	L"RUN_FORWARD",
	L"RUN_BACK",
	L"RUN_RIGHT",
	L"RUN_LEFT",
	L"JUMP",
	L"IDLE",
	L"ATTACK1",
	L"ATTACK2",
	L"ATTACK3",
	L"ATTACK4",
	L"DIE",
	L"DEAD",
	L"EXTRA1",
	L"EXTRA2",
	L"EXTRA3",
	L"EXTRA4",
	L"NONE",
};
